site_name: Artificial Neural Networks and Deep Learning
site_description: "Artificial Neural Networks and Deep Learning course at Insper"
site_author: Sandmann, H.
site_url: https://insper.github.io/ann-dl
repo_url: https://github.com/insper/ann-dl
repo_name: insper/ann-dl

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  logo: assets/images/ann-dl.png

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - neoteroi.timeline
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables


plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: insper/ann-dl
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - search: {}
  - encryptcontent: {}
  - minify:
      minify_html: true
  - badges
  - markdown-exec
  - plotly
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.min.css
  - assets/stylesheets/neoteroi-timeline.css
  - assets/stylesheets/extra.css

nav:
  - Ementa: index.md
  - 2025.2: versions/2025.2/index.md

  - Classes:
    - 1. Concepts: ./classes/concepts/index.md
    - 2. Data: ./classes/data/index.md
    - 3. Preprocessing: ./classes/preprocessing/index.md
    - 4. Neural Networks: ./classes/ann/index.md
    - 5. Perceptron: ./classes/perceptron/index.md
    - 6. Multi-Layer Perceptron: ./classes/mlp/index.md
    - 7. Optimization: ./classes/optimization/index.md
    - 8. Regularization: ./classes/regularization/index.md
    - 9. Metrics and Evaluation:
      - 9.1. Classification: ./classes/metrics/classification/index.md
      - 9.2. Regression: ./classes/metrics/regression/index.md
      # - 4.3. Model Evaluation: ./classes/metrics/model-evaluation.md
      # - 4.4. Cross-Validation: ./classes/metrics/cross-validation.md
      # - 4.5. Hyperparameter Tuning: ./classes/metrics/hyperparameter-tuning.md
    - 10. Deep Learning: ./classes/deep-learning/index.md
    - 11. Convolutional: ./classes/convolutional-neural-networks/index.md
    - 12. Generative Models: ./classes/generative-models/index.md
    - 13. GAN: ./classes/generative-adversarial-networks/index.md
    - 14. VAE: ./classes/variational-autoencoders/index.md
    - 15. CLIP: ./classes/clip/index.md
    - 16. Stable Diffusion: ./classes/stable-diffusion/index.md

  # - 11. Transfer Learning: ./classes/deep-learning/transfer-learning.md
  # - 12. Recurrent Neural Networks: ./classes/deep-learning/rnn.md
  # - 13. Long Short-Term Memory Networks: ./classes/deep-learning/lstm.md
  # - 14. Attention Mechanisms: ./classes/deep-learning/attention.md
  # - 15. Transformers: ./classes/deep-learning/transformers.md
  # - 16. Natural Language Processing: ./classes/deep-learning/nlp.md
  # - 17. Computer Vision: ./classes/deep-learning/cv.md
  # - 18. Reinforcement Learning: ./classes/deep-learning/reinforcement-learning.md

  - Definitions: 
    - Latent Space vs. Embedding: definitions/latent_space_vs_embedding.md
    # - Overfitting vs. Underfitting: definitions/overfitting_vs_underfitting.md
    # - Batch Size vs. Epochs: definitions/batch_size_vs_epochs.md
    # - Learning Rate vs. Momentum: definitions/learning_rate_vs_momentum.md
    # - Precision vs. Recall vs. F1-Score: definitions/precision_vs_recall_vs_f1score.md

  - References: references.md

  - Versions:
    - Terms and Conditions: versions/terms-and-conditions.md
    - 2025.2:
      - Presentation: ./versions/2025.2/index.md
      - Exercises:
        - 1. Data: ./versions/2025.2/exercises/data/index.md
        - 2. Perceptron: ./versions/2025.2/exercises/perceptron/index.md
        - 3. MLP: ./versions/2025.2/exercises/mlp/index.md
        - 4. VAE: ./versions/2025.2/exercises/vae/index.md
      - Projects:
        - 1. Classification: ./versions/2025.2/projects/classification/index.md
        - 2. Regression: ./versions/2025.2/projects/regression/index.md
        - 3. Generative: ./versions/2025.2/projects/generative/index.md
